apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{APP_NAME}}
spec:
  serviceName: {{SVC_NAME}}
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{APP_NAME}}
        image: {{IMAGE_NAME}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 30m # 300m
            memory: 100Mi # 5120Mi
        # livenessProbe:
        #   exec:
        #     command: ["rabbitmqctl", "status"]
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        # readinessProbe:
        #   exec:
        #     command: ["rabbitmqctl", "status"]
        #   initialDelaySeconds: 20
        #   timeoutSeconds: 5
        ports:
          - name: queue-port
            containerPort: 5672
          - name: management-port
            containerPort: 15672
          - name: cluster-port
            containerPort: 4369
          - name: dist-port
            containerPort: 25672
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: {{RABBITMQ_DEFAULT_USER}}
          - name: RABBITMQ_DEFAULT_PASS
            value: "{{RABBITMQ_DEFAULT_PASS}}"
          - name: RABBITMQ_LOG_LEVEL
            value: "{{RABBITMQ_LOG_LEVEL}}"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "{{RABBITMQ_ERLANG_COOKIE}}"
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: RABBITMQ_HA_POLICY
            value: '{{RABBITMQ_HA_POLICY}}'
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RABBITMQ_NODENAME
            value: rabbit@$(NODE_NAME).{{SVC_NAME}}
      {{SERVICE_ACCOUNT}}
      {{ADDITIONAL_YAML}}
